[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && python start.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
